name: update algolia
on:
  push:
    branches: [ main ]
jobs:
  update-algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Update Algolia index
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: 'hugo-index'
          ALGOLIA_INDEX_FILE: './index.json'
        run: npm run algolia
